import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Countdown Timer",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',  // Favicon link
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
